### ISSUE TITLE
Todo 리스트

### ISSUE THREAD

**Issue by bigbreadguy** [bigbreadguy/simple-prj-editor#5]
## Todo
- [x] csv 임포트를 위한 upload 버튼 만들기 @bigbreadguy 
- [x] flow elements 치트 시트 만들기 @bigbreadguy 
- [ ] 리드미 추가 @hstone-Jo 

## mito sheet 관련 이슈
- 화면에 출력된 전체 행 수정 기능이 디폴트이고 별도의 옵션이 없음 -> 수정을 외부에서 하도록 안내
- 필터를 해제하지 않고 데이터 다운로드 시 필터링 된 데이터만 포함되어 변환 -> 수정을 외부에서 하도록 안내
- csv, excel 임포트는 서버의 파일 시스템에 대해서만 가능함

## flow elements 관련 이슈
- 해당 섹션을 시트에 출력해 줄 것인지
- 데이터 형식이 다른 섹션과 달라서 데이터 프레임으로 파싱하는 건 적절치 못함
- 아이디(자연수)와 이름(AD, E.VDOOR 등)으로 추정되는 두 열만 뽑아서 dict로 쓰면 될 것 같음
-> 파싱한 딕셔너리를 스트림릿 앱에 출력해주기 

## 기타
- 화면에 출력된 데이터 프레임에서 제외할 열이 있는지
